language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.1

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - mvn clean install -P 'guice'
