language: android
jdk: oraclejdk7

# http://blog.xeiam.com/2013/05/configure-travis-ci-to-deploy-snapshots.html
env:
    global:
        - secure: "MBolkGQu4J/ZU6HuUv/kUkssmlIgKQ22Wn4njYHqSrWbfpFKHhFR4T3iSrA1YSqExy2QZ1UWWe4dHAypkbtkamuvawvS/h1JcPbgwkBCekkz3FD11AOI35E2GahbEoUphHC2OG4qZGJ2RcwCUyLaPKZJNIAIzc/dV15mWv6QgVA="
        - secure: "RCklprdsC5v87r76/jWexKzdcZbLLeUh2JyR7bako8lYtIjs2yhVofMxUenY3rQCVbMWyR68Je5uH4rNENmqqZZnG3hgb/yHNn/FMFuFDiGyaRMZbGjPYZy47nsfI89i8KWr8P8hT1Ro90Mp+Q/QOQu0Eca6VWZtSNTraxor0dc="


before_install:
    - git clone -b travis `git config --get remote.origin.url` target/travis

android:
  components:
    - build-tools-19.0.1
#    - android-19
#    - android-17

#build guice fork before building RG
before_script:
    - cd guice
    - mvn clean install -DskipTests=true -Djavadoc.skip=true
    - cd ..

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - if [ "$TRAVIS_BRANCH" == "master" -a "TRAVIS_PULL_REQUEST" == "false" ] ; then mvn deploy --settings target/travis/settings.xml ; else mvn install --settings target/travis/settings.xml ; fi
